---
title: "Lake Report Template"
author: "Daniel Nidzgorski"
date: "October 27, 2017"
output:
  html_notebook: default
  github_document: default
params:
  lake: Angle
  year: 2017
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(stringr)
source("Multiplot function.R")
source("Annual plotting function.R")
```
```{r Set up data, include=FALSE}
# This looks for a "Small Lake Data" csv file in the directory
# from the web/SQL database

datafile<-list.files() %>%
  {Filter(x=.,function(d) str_detect(d,"Small Lake Data"))}
input<-read_csv(datafile,
         col_types=cols(
           .default = col_double(),
           SiteName = col_character(),
           CollectDate = col_datetime(format = ""),
           DepthQ = col_character(),
           SecchiQ = col_character(),
           TempQ = col_character(),
           ChloroQ = col_character(),
           PheophQ = col_character(),
           TotalNQ = col_character(),
           NO23Q = col_character(),
           NH3NQ = col_character(),
           TotalPQ = col_character(),
           OPO4Q = col_character(),
           UV254Q = col_character(),
           TotalAlkQ = col_character(),
           AnatoxinQ = col_character(),
           MicrocystinQ = col_character()
         )
) %>%
  rename(Lake=SiteName,
         Date=CollectDate) %>%
  mutate(Date=as.Date(Date))

data<-input %>%
  gather(-Lake,-Date,-Depth,
         key=Parameter,value=Value) %>%
  filter(!str_detect(Parameter,"Q")) %>%
  mutate(Value=as.numeric(Value))# remove quals
```

```{r Testing the plotting function, eval=FALSE}
lake<-params$lake
year<-params$year
param<-"Secchi"
wy<-F

ap<-annual.plot(data,lake="Angle",year=2017,param="NPRatio")
ap
```

```{r Generate annual plots, message=F,warning=F}
annual.params<-c("Secchi",
                 "Temperature",
                 "TotalNitrogen",
                 "TotalPhosphorus",
                 "NPRatio",
                 "ChlorophyllA"
)

annual.plots.list<-map(annual.params,annual.plot,
                      data=data,lake=params$lake,year=params$year,wy=F)
multiplot(plotlist=annual.plots.list,cols=1)
```

